### ISSUE TITLE
ToDo Relation ships

### ISSUE THREAD

**Issue by YaminMECHQI** [YaminMECHQI/ecom-local#2]
- [ ]  create category CRUD
- [ ]  get category products (table)
- [ ]  create Supplier Entity with CRUD with relationships ( OneToMany Product )
